var abi = /* abi generated by compiler */;
var ClientReceipt = web3.eth.contract(abi);
var clientReceipt = ClientReceipt.at("0x000" /*addy*/);
var depositEvent = clientReceipt.Deposit();

//watch for new changes
depositEvent.watch(function(error, result){
   if(!error)
      console.log(result);
});

//pass a callback to start watching immediatly
var depositEvent = clientReceipt.Deposit(function(error, result){
    if(!error)
      console.log(result);
});
